name: Build and Release BreakSchedulerQt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        target: desktop
        arch: win64_msvc2019_64

    - name: Install CMake
      uses: lukka/get-cmake@v3

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Deploy Qt DLLs
      run: |
        windeployqt build/Release/BreakSchedulerQt.exe

    - name: Zip artifacts
      run: |
        Compress-Archive -Path build/Release/* -DestinationPath BreakSchedulerQt.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: BreakSchedulerQt.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
